os: linux
language: C++
dist: focal
install:
  - curl --progress-bar --ipv4 --connect-timeout 8 --max-time 120 --retry 128 https://codestation.org/travis/yaal-bundle.tar --output yaal-bundle.tar
  - tar xvpf yaal-bundle.tar
  - export BUNDLE=`tar tf yaal-bundle.tar`
  - tar xvpf "${BUNDLE}"
  - export OS=`echo "${BUNDLE}" | awk -F '-' '{print $3"-"$4}'`
  - export ARCH=`echo "${BUNDLE}" | awk -F '-' '{print $5}' | awk -F '.' '{print $1}'`
  - export VER=`echo "${BUNDLE}" | awk -F '-' '{print $2}'`
  - sudo dpkg -i yaal-bundle/${OS}/${ARCH}/${VER}/yaal{,-dev}_*.deb
script:
  - umask 0077
  - export TIMESTAMP=`date +%Y%m%d%H%M%S`
  - export PREFIX="${HOME}/usr" SYSCONFDIR="${HOME}/etc/conf" LOCALSTATEDIR="${HOME}/var"
  - ./setup.sh
  - make
  - make -C _deploy/debian clean package bundle BUILD_ID="-0codestation${TIMESTAMP}"
  - while ! lftp -e 'set xfer:timeout 4;set net:timeout 4;set net:persist-retries 1024;set net:max-retries 1024;set ftp:prefer-epsv false;set ftp:passive-mode true;put debian/tmp/huginn-bundle.tar;quit' -u "travis,${TRAVIS_FTP_PASS}" codestation.org ; do true ; done
addons:
  apt:
    packages:
      - libedit-dev
      - libxml2-utils
      - xmlto
      - xsltproc
      - devscripts
      - libdistro-info-perl
      - dpkg-dev
      - fakeroot
      - debhelper
      - asciidoctor
      - lftp
      - curl
sudo: true
cache:
  ccache: true

