#! /bin/sh

HUGINN_ROOT="./src"

set -- "/usr/share/huginn" "/usr/local/share/huginn"

if [ ! -f "${HUGINN_ROOT}/ihuginn.py" ] ; then
	for path do
		if [ -d "${path}" ] ; then
			HUGINN_ROOT="${path}"
			break
		fi
	done
else
	HUGINN_ROOT="`pwd`/src"
fi

if [ ! -f "${HUGINN_ROOT}/ihuginn.py" ] ; then
	echo "Huginn auxilary files root directory has not been found!"
	exit 1
fi

invoke() {
	echo "${@}"
	eval "${@}"
}

set -e

SITE_DIR=`python3 -m site --user-site`
DIST_DIR=`python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`
if [ -d "${SITE_DIR}" ] ; then
	DEST_DIR="${SITE_DIR}"
else
	DEST_DIR="${DIST_DIR}"
	SUDO="sudo"
fi

umask 022

invoke jupyter notebook --generate-config
invoke mkdir -m 755 -p ${HOME}/.ipython/kernels
invoke mkdir -m 755 -p ${HOME}/.jupyter/custom
invoke ln -nsf "${HUGINN_ROOT}" ${HOME}/.ipython/kernels/huginn
invoke ${SUDO} ln -sf "${HUGINN_ROOT}/ihuginn.py" "${DEST_DIR}/"
invoke ${SUDO} ln -sf "${HUGINN_ROOT}/pygment.py" "${DEST_DIR}/pygments/lexers/huginn.py"
invoke ${SUDO} ln -sf "${HUGINN_ROOT}/pygment.py" "${DEST_DIR}/pygments/styles/huginn.py"
cd "${DEST_DIR}/pygments/lexers"
invoke ${SUDO} python3 ./_mapping.py
cd -
invoke ${SUDO} mkdir -m 755 -p "${DEST_DIR}/notebook/static/components/codemirror/mode/huginn"
invoke ${SUDO} ln -sf "${HUGINN_ROOT}/codemirror.js" "${DEST_DIR}/notebook/static/components/codemirror/mode/huginn/huginn.js"
invoke ${SUDO} ln -sf "${HUGINN_ROOT}/jupyter.css" "${HOME}/.jupyter/custom/custom.css"
invoke ${SUDO} mkdir -m 755 -p "${HOME}/var/db/jupyter" "${HOME}/var/root" "${HOME}/var/notebooks"

cat >> "${HOME}/.jupyter/jupyter_notebook_config.py" << EOF
c.NotebookApp.ip = '0.0.0.0'
c.NotebookApp.allow_origin = 'http://127.0.0.1:8888'
c.NotebookApp.base_url = '/huginn-notebook/'
c.MappingKernelManager.root_dir = '${HOME}/var/root/'
c.FileContentsManager.root_dir = '${HOME}/var/notebooks/'
c.NotebookNotary.db_file = '${HOME}/var/db/jupyter/nbsignatures.db'
c.NotebookApp.open_browser = False
EOF

cat >> "${HOME}/.jupyter/jupyter_console_config.py" << EOF
c.ZMQTerminalInteractiveShell.highlighting_style = "huginn"
EOF

