#! /bin/sh

HUGINN_ROOT="./src"

set -- "/usr/share/huginn" "/usr/local/share/huginn"

if [ ! -f "${HUGINN_ROOT}/ihuginn.py" ] ; then
	for path do
		if [ -d "${path}" ] ; then
			HUGINN_ROOT="${path}"
			break
		fi
	done
else
	HUGINN_ROOT="`pwd`/src"
fi

if [ ! -f "${HUGINN_ROOT}/ihuginn.py" ] ; then
	echo "Huginn auxilary files root directory has not been found!"
	exit 1
fi

invoke() {
	echo "${@}"
	eval "${@}"
}

set -e

PIP_DIR=`python3 -m site --user-site`

invoke jupyter notebook --generate-config
invoke mkdir -p ${HOME}/.ipython/kernels
invoke mkdir -p ${HOME}/.jupyter/custom
invoke ln -nsf "${HUGINN_ROOT}" ${HOME}/.ipython/kernels/huginn
invoke ln -sf "${HUGINN_ROOT}/ihuginn.py" "${PIP_DIR}/"
invoke ln -sf "${HUGINN_ROOT}/pygment.py" "${PIP_DIR}/pygments/lexers/huginn.py"
invoke ln -sf "${HUGINN_ROOT}/pygment.py" "${PIP_DIR}/pygments/styles/huginn.py"
cd "${PIP_DIR}/pygments/lexers"
invoke python3 ./_mapping.py
cd -
invoke mkdir -p "${PIP_DIR}/notebook/static/components/codemirror/mode/huginn"
invoke ln -sf "${HUGINN_ROOT}/codemirror.js" "${PIP_DIR}/notebook/static/components/codemirror/mode/huginn/huginn.js"
invoke ln -sf "${HUGINN_ROOT}/jupyter.css" "${HOME}/.jupyter/custom/custom.css"
invoke mkdir -p "${HOME}/var/db/jupyter" "${HOME}/var/root" "${HOME}/var/notebooks"

cat >> "${HOME}/.jupyter/jupyter_notebook_config.py" << EOF
c.NotebookApp.ip = '*'
c.NotebookApp.allow_origin = 'http://127.0.0.1:8888'
c.NotebookApp.base_url = '/huginn-notebook/'
c.MappingKernelManager.root_dir = '${HOME}/var/root/'
c.FileContentsManager.root_dir = '${HOME}/var/notebooks/'
c.NotebookNotary.db_file = '${HOME}/var/db/jupyter/nbsignatures.db'
c.NotebookApp.open_browser = False
EOF

cat >> "${HOME}/.jupyter/jupyter_console_config.py" << EOF
c.ZMQTerminalInteractiveShell.highlighting_style = "huginn"
EOF

