#! /bin/sh

if [ ! -f ./src/ihuginn.py ] ; then
	echo "This script must be executed from project root direcotory."
	exit 1
fi

invoke() {
	echo "${@}"
	eval "${@}"
}

set -e

CUR_DIR=`pwd`
PIP_DIR=`python3 -m site --user-site`

invoke jupyter notebook --generate-config
invoke mkdir -p ${HOME}/.ipython/kernels
invoke ln -nsf "${CUR_DIR}/src" ${HOME}/.ipython/kernels/huginn
invoke ln -sf "${CUR_DIR}/src/ihuginn.py" "${PIP_DIR}/"
invoke ln -sf "${CUR_DIR}/src/pygment.py" "${PIP_DIR}/pygments/lexers/huginn.py"
cd "${PIP_DIR}/pygments/lexers"
invoke python3 ./_mapping.py
cd -
invoke mkdir -p "${PIP_DIR}/notebook/static/components/codemirror/mode/huginn"
invoke ln -sf "${CUR_DIR}/src/codemirror.js" "${PIP_DIR}/notebook/static/components/codemirror/mode/huginn/huginn.js"
invoke mkdir -p "${HOME}/var/root" "${HOME}/var/notebooks"

cat >> "${HOME}/.jupyter/jupyter_notebook_config.py" << EOF
c.NotebookApp.allow_origin = 'http://127.0.0.1:8888'
c.NotebookApp.base_url = '/huginn-notebook/'
c.MappingKernelManager.root_dir = '${HOME}/var/root/'
c.FileContentsManager.root_dir = '${HOME}/var/notebooks/'
c.NotebookApp.open_browser = False
EOF

