#ifndef HUGINN_LOCAL_HXX_INCLUDED
#define HUGINN_LOCAL_HXX_INCLUDED 1

#ifdef HUGINN_CONFIG_HXX_INCLUDED
#cmakedefine HAVE_REPLXX_H
#endif /* #ifdef HUGINN_CONFIG_HXX_INCLUDED */

#endif /* #ifndef HUGINN_LOCAL_HXX_INCLUDED */

